name: Artifacts

on:
  push

jobs:
  build:
    name: Build binaries
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ 1.15.x ]
        os: [ linux, darwin, windows ]
        architecture: [ amd64 ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Fetch dependencies
        run: go mod vendor

      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.architecture }} make build

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-${{ matrix.architecture }}
          path: xud-launcher
