name: Artifacts

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build artifacts
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ 1.15.x ]
        os: [ linux, darwin, windows ]
        architecture: [ amd64 ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Fetch dependencies
        run: go mod vendor

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.architecture }} VERSION=${{ steps.get_version.outputs.VERSION }} make build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.architecture }}
          path: |
            xud-launcher
            xud-launcher.exe
